### ISSUE TITLE
Search functionality in labels and therapy stubs

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#14]
I need the possibility to perform a fulltext search in the fields of the labels or the therapy stubs

**Comment by pmeng** [comment]
The search in labels is already implemented. But the search in the therapy stubs is broken and not working
![image](https://user-images.githubusercontent.com/1121561/222059736-a63ceefe-7038-496a-a82d-4e33c5a775fc.png)
Additionally, we need a third search box, for a fulltext search in the saved therapy schemes.

**Comment by DhiaDjobbi** [comment]
Fixed on:
https://github.com/pmeng/therapy-scheme-generator/pull/23
