### ISSUE TITLE
Saved template shall be editable

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#18]
When loading a saved therapy scheme, I want to be able to edit it again. So, i want to be able to search for labels and add them to the scheme.
Additionally, I want to be able to save the template (using the former template name) or to run "save as" to save it using a new name.

**Comment by DhiaDjobbi** [comment]
Done.

![2023-04-02 06-43-54](https://user-images.githubusercontent.com/40583006/229333997-2995306d-c0e9-4bb7-8216-8ea01c829b20.gif)

**Comment by pmeng** [comment]
done.
