### ISSUE TITLE
Toggle switches "Suppress labels" and "Use excerpt" are not working

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#19]
In the view "New therapy scheme" but also when loading a saved therapy scheme, the toggle switches are not working. 
![image](https://user-images.githubusercontent.com/1121561/218335317-aed8d68a-efdb-4a4c-aeb7-19fb52f343a8.png)

**Comment by DhiaDjobbi** [comment]
Fixed.

![2023-04-02 05-37-24](https://user-images.githubusercontent.com/40583006/229331686-eee1784a-64fd-40fb-9357-be5a75560ff3.gif)

**Comment by pmeng** [comment]
Tested it - they are not suppressed in the pdf view. Can you please fix this?

**Comment by pmeng** [comment]
fixed.
