### ISSUE TITLE
Change the list view of the therapy stubs list

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#20]
In the Therapy stubs list, only the Name, Description and Background of the therapy stub is shown, the excerpt and the labels are missing.

![image](https://user-images.githubusercontent.com/1121561/222060429-26c8f71f-2b59-48b1-ac93-0825f5f76106.png)

![image](https://user-images.githubusercontent.com/1121561/222060605-d4675b4a-bcb5-4f03-ba68-c03f0bee9a52.png)

I want the excerpt and the labels to be shown as well. As this is a lot of data, the view should be changed to a tabular view with one therapy stub in each line with the corresponding data in the cols.
Additionally I want to have some kind of "quick search" implemented in the headers of the columns where I can perform a fulltext search in the corresponding columns (if there are more pages of therapy stubs, i want that this quick search ist performed in all pages and not only the one page i am currently on)

**Comment by DhiaDjobbi** [comment]
Hi, are you trying to build something like this:

![image](https://user-images.githubusercontent.com/40583006/224128032-2a8ca04e-7f07-4bb6-b134-1c755fbcdeba.png)

If yes, then I want to ask you what field do you want to searchBy? 
(Name OR Description OR exerpt..)
Or is it MultiFields Search?

**Comment by pmeng** [comment]
Kind of. I dont need to see the created at date
I want one search field for everything and additionally one search field per column
