### ISSUE TITLE
List Assigned Therapy Stubs to Labels

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#21]
In the View "Edit Label" i want to see a List of the therapy stubs that this label is associated with
![image](https://user-images.githubusercontent.com/1121561/224475540-0eec06a0-d862-4bb0-ad6b-4627b6400d81.png)

**Comment by Mahmoudnaoum** [comment]
you want to make it clickable and direct to the stub page or not?
