### ISSUE TITLE
Create new label in therapy stub

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#33]
wanted behaviour: when entering a new label name in the dialog to add a new therapy stub, the software shall create that label in the database if it does not exist.
At the moment an error message is given:
![image](https://user-images.githubusercontent.com/1121561/234358353-76089b33-63f9-49f6-8e63-587f8da813a2.png)

**Comment by DhiaDjobbi** [comment]
Should be fixed in [**this pull request**](https://github.com/pmeng/therapy-scheme-generator/pull/36).
