### ISSUE TITLE
Change the Output of the Therapy Schemes

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#35]
The output of the therapy schemes is at the moment exactly the same as in the list.
I need the output to be changed to a format like:

###START
HEADER

Description (resp. Excerpt)
Comment

Description (resp. Excerpt)
Comment

Description (resp. Excerpt)
Comment

…
###END

It should only output the selected Therapy Stubs. 
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/b97c9016-c154-4647-8dfa-58c8bd3ce5d3)

It shall use the Formatting defined in these stubs.
Between Description and Comment is a linebreak
Between Comment and the next Description is blank line

When "use excerpt instead of description" is selected, then instead of the description the "excerpt" is printed.

The "HEADER" shall be customizable - for now it is good if it is possible to define some HTML Code that is being embedded - can also be a HTML file that is located on the server and when customizations are needed, they are performed in this html file.

**Comment by DhiaDjobbi** [comment]
Hi,
The description you provided is quite vague and general, making it difficult for me to implement the changes accurately.
I kindly request you to provide a detailed example or a mockup (maquette) illustrating the desired output format.

This will help me better understand the specific changes you want and ensure that I can deliver the expected results.

**Comment by pmeng** [comment]
Okay, so I try to express myself more clear.
I generated some test content for that, so i can demonstrate it better.

In the form "New therapy scheme" I selected 2 labels to generate a new report
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/c0c27d0d-ea57-4c36-b8c7-4d8bc17c9b91)

Here you can see, that  I selected 2 therapy stubs in label "test" and 1 therapy stub in label "test_2".
All the other stubs are not selected.

Now I click on generate report (PDF), and this is being generated:
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/ebe14ee8-a7b2-4899-9a53-0cbefe63f72d)


I need the report to be different.
In the following mockup i striked through all fields that are not needed on the report:
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/ec861074-a0a2-4489-b95d-35b586a6c795)

So, the final report should look like:
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/0729577c-8281-4c85-9beb-64da1e064a06)

I made another mockup that show how the content in the comment field should be displayed:
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/6e2faefe-7033-496c-b27b-fa80d779a13f)
current report:
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/0112699f-560f-4b71-9227-3cb5ed89ef7d)

desired result:
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/06d9c2e0-455e-4f1b-b256-0720b6becb47)


The switch "Suppress Labels" shall suppress labels in the report - so the functionality of this switch should not be removed
The switch "user excerpt instead of description" changes just the output - instead of the text contained in the field "description" - so it should work as currently implemented.
