### ISSUE TITLE
Update the output of a therapy Scheme

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#65]
Currently therapy scheme output is as following:

Label Name | Therapy Stub Content

Please change the output to only print the therapy stub content
![image](https://github.com/pmeng/therapy-scheme-generator/assets/1121561/76433ecb-3b6d-424d-b3d9-9d7ff37acdd1)

**Comment by Mahmoudnaoum** [comment]
Do you mean removing the Stub name from the output and print only the stub content like this :
![image](https://github.com/pmeng/therapy-scheme-generator/assets/47036731/87dc0411-6e4c-48cc-9c32-56009f4da7ee)
