### ISSUE TITLE
Change CKEditor to alternative Editor

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#88]
CKEditor is not free anymore. 
Please remove CKEditor and use NicEdit instead

**Comment by Mahmoudnaoum** [comment]
The current version is still free; however, the open-source version no longer includes security updates, which puts your application at risk. Therefore, I suggest upgrading to the paid version (4.24.0). In the meantime, you can continue using the free version, and I will work on migrating to NicEdit, which will work for you without any additional costs.

**Comment by pmeng** [comment]
fixed
