### ISSUE TITLE
Updating a therapy scheme does not save all entries

### ISSUE THREAD

**Issue by pmeng** [pmeng/therapy-scheme-generator#89]
When a therapy scheme is updated, not all categories are saved. Please check.

**Comment by Mahmoudnaoum** [comment]
Could you provide more clarification or mention a specific scenario where this occurs?

**Comment by leo7422g** [comment]
When updating a therapy scheme, not all entries are being saved. This issue can lead to incomplete records, which may affect the accuracy and continuity of treatment plans. It's crucial to identify and resolve the underlying cause of this problem to ensure that all therapy details are correctly documented and maintained here [https://rubmd.net/](https://rubmd.net/). Without a reliable saving mechanism, there is a risk of critical information being lost or overlooked, potentially impacting patient care and outcomes.

**Comment by Mahmoudnaoum** [comment]
Sure, I'm working on it now. I've got my hands on the issue, and it will be fixed soon.

**Comment by pmeng** [comment]
fixed
